### ISSUE TITLE
`get_irods_path` not working for season 10

### ISSUE THREAD

**Issue by emmanuelgonz** [phytooracle/automation#26]
`get_irods_path` is not working for season10 (specfically for the `yaml_files/season_10/example_machinelearning_workflow_normalizatiod_fixes.yaml` file). The error repoted is as follows: 

>  Traceback (most recent call last):                                                                                      File "./distributed_pipeline_wrapper.py", line 953, in <module>                                                         main()                                                                                                              File "./distributed_pipeline_wrapper.py", line 906, in main                                                             irods_path = get_irods_path(dictionary, date)                                                                       File "./distributed_pipeline_wrapper.py", line 165, in get_irods_path                                                   Found: {matching_files}")
ValueError: Could not find appropriate tarball for date: 2020-03-02
                            Found: []

**Comment by emmanuelgonz** [comment]
@equant I tracked the issue down to the following lines within the `download_raw_data` function:

>     if any(x in tarball_filename for x in gzip_extensions):
#     if gzip_extension in tarball_filename:
        command = f"tar -ztf {tarball_filename}"
    else:
        command = f"tar -tf {tarball_filename}"

Are we okay pushing these changes to `main`?
