### ISSUE TITLE
Error with join during pipeline run

### ISSUE THREAD

**Issue by emmanuelgonz** [phytooracle/automation#61]
After running the following command:
`./distributed_pipeline_wrapper.py -hpc -d 2222-22-22 -y yaml_files/season_11/3d_pre_landmark_selection.yaml`

I get the following error:

> Traceback (most recent call last):
>   File "./distributed_pipeline_wrapper.py", line 1055, in <module>
>     main()
>   File "./distributed_pipeline_wrapper.py", line 1000, in main
>     download_irods_input_dir(dictionary, date, args)
>   File "./distributed_pipeline_wrapper.py", line 184, in download_irods_input_dir
>     irods_input_dir_path = os.path.join(sensor_path, date, input_dir)
>   File "/usr/lib64/python3.6/posixpath.py", line 94, in join
>     genericpath._check_arg_types('join', a, *p)
>   File "/usr/lib64/python3.6/genericpath.py", line 149, in _check_arg_types
>     (funcname, s.__class__.__name__)) from None
> TypeError: join() argument must be str or bytes, not 'list'

The error seems to be due to an issue when creating the irods data path. The variable `input_dir` is an empty list, so `os.path.join` errors out.

**Comment by emmanuelgonz** [comment]
@equant I tested the branch, and it resolved the issue. Data downloaded, workers launched, and pipeline ran. We can merge with `main` unless @Travis-Simmons had any problems with it.

**Comment by Travis-Simmons** [comment]
I tested the branch and had problems with workers launching, however I don't think I gave it enough time. If @emmanuelgonz got it working I am good with it being merged.
