### ISSUE TITLE
OS lookup for CCTools download fails on CentOS

### ISSUE THREAD

**Issue by emmanuelgonz** [phytooracle/automation#77]
I get the following error when running PO automation on CentOS:

> Traceback (most recent call last):
>   File "./distributed_pipeline_wrapper.py", line 1227, in <module>
>     main()
>   File "./distributed_pipeline_wrapper.py", line 1110, in main
>     cctools_path = download_cctools(cctools_version=args.cctools_version)
>   File "./distributed_pipeline_wrapper.py", line 122, in download_cctools
>     if platform.linux_distribution()[0] != 'CentOS Linux':
> AttributeError: module 'platform' has no attribute 'linux_distribution'

We will need to address this ASAP in order to process season 10 data on gpu06.

**Comment by emmanuelgonz** [comment]
This issue is present in Python3.8, not Python3.6. May want to update our code to a solution that supports any Python version.

**Comment by equant** [comment]
As of Python 3.5 `platform.linux_distribution` is deprecated.  It's suggested to use `distro.linux_distribution()` for 3.8, but then that was deprecated _and_ `distro` isn't part of what's available by default on the hpc, so I created within our `server_utils` library `server.utils.distro_name()` which grabs the info from `/etc/os-release` which is how all the other libraries do it anyway.  Tested and working for me on hpc.  Not tested anywhere else.

**Comment by emmanuelgonz** [comment]
@Travis-Simmons Let us know how this works on `gpu06`
